name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint quick check (flake8 optional)
        run: |
          pip install flake8 || true
          flake8 || true

      - name: Import test
        run: |
          python - << 'PY'
          import importlib.util, sys, pathlib
          p = pathlib.Path("resume_dashboard_teja/app.py").resolve()
          spec = importlib.util.spec_from_file_location("app", p)
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print("Imported app.py successfully")
          PY
